services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db_2
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -uroot -p$MYSQL_ROOT_PASSWORD --silent"
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres_historico:
    image: postgres:16
    container_name: postgres_historico
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${HISTORICO_DB_NAME}
      POSTGRES_USER: ${HISTORICO_DB_USERNAME}
      POSTGRES_PASSWORD: ${HISTORICO_DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_historico_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${HISTORICO_DB_USERNAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    image: apache/kafka:4.1.1
    container_name: kafka_2
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka_2:29092,EXTERNAL://localhost:9092,CONTROLLER://kafka_2:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka_2:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    ports:
      - "9092:9092"
    volumes:
      - kafka-data:/var/lib/kafka/data
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "nc -z localhost 9092 || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 40s

  kafdrop:
    image: obsidiandynamics/kafdrop:4.1.0
    container_name: kafdrop_2
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: kafka_2:29092
    depends_on:
      - kafka
    networks:
      - app-network

  agendamento:
    build:
      context: ./agendamento
      dockerfile: Dockerfile
    image: aira17/agendamento:latest
    container_name: agendamento-service
    ports:
      - "8080:8080"   #http
    env_file:
      - .env
    environment:
      SPRING_MONGODB_URI: mongodb+srv://${MONGO_USERNAME}:${MONGO_PASSWORD}@cluster0.9rwot.mongodb.net/${MONGO_DATABASE}?retryWrites=true&w=majority
      SPRING_DATA_MONGODB_DATABASE: ${MONGO_DATABASE}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka_2:29092
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  notificacao:
    build:
      context: ./notificacao
      dockerfile: Dockerfile
    image: aira17/notificacao:latest
    container_name: notificacao-service
    ports:
      - "5005:5005"   #debug
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka_2:29092
      SPRING_MAIL_HOST: smtp.gmail.com
      SPRING_MAIL_PORT: 587
      SPRING_MAIL_USERNAME: ${MAIL_USERNAME}
      SPRING_MAIL_PASSWORD: ${MAIL_PASSWORD}
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    depends_on:
      mysql:
        condition: service_healthy
      kafka:
        condition: service_healthy
    networks:
      - app-network

  historico:
    build:
      context: ./historico
      dockerfile: Dockerfile
    image: aira17/historico:latest
    container_name: historico-service
    ports:
      - "8081:8081"   #graphql
      - "5006:5006"   #debug
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka_2:29092
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_historico:5432/${HISTORICO_DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${HISTORICO_DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${HISTORICO_DB_PASSWORD}
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5006
    depends_on:
      kafka:
        condition: service_healthy
      postgres_historico:
        condition: service_healthy
    networks:
      - app-network

volumes:
  mysql_data:
  kafka-data:
  postgres_historico_data:

networks:
  app-network:
    driver: bridge
